use {
    anyhow::{Context as _, Result},
    clap::Args,
    log::info,
    reqwest::blocking::Client,
    serde::Deserialize,
    std::{
        cmp,
        fmt::Write as _,
        fs,
        path::{Path, PathBuf},
    },
};

const STAKEWIZ_VALIDATORS_URL: &str = "https://api.stakewiz.com/validators?limit=2500";

#[derive(Args)]
pub struct CommandArgs {
    #[arg(
        short,
        long,
        default_value = "runtime/benches/epoch_turnover_mainnet.rs"
    )]
    pub output_file: PathBuf,
}

#[derive(Debug, Deserialize)]
struct Validator {
    activated_stake: f64,
}

/// Fetches information about mainnet validators and their activated stake.
fn fetch_mainnet_validators() -> Result<Vec<Validator>> {
    let client = Client::builder()
        .timeout(std::time::Duration::from_secs(20))
        .build()
        .context("failed to build HTTP client")?;
    let response = client
        .get(STAKEWIZ_VALIDATORS_URL)
        .send()
        .with_context(|| {
            anyhow::anyhow!("failed to send the request to {STAKEWIZ_VALIDATORS_URL}")
        })?
        .error_for_status()
        .with_context(|| {
            anyhow::anyhow!("request to {STAKEWIZ_VALIDATORS_URL} returned a non-success status")
        })?;
    let mut validators: Vec<Validator> = response
        .json()
        .context("failed to parse Stakewiz validator JSON")?;
    validators.sort_unstable_by(|left, right| {
        right
            .activated_stake
            .partial_cmp(&left.activated_stake)
            .unwrap_or(cmp::Ordering::Equal)
    });

    Ok(validators)
}

/// Renders Rust code with a fixture based on mainnet validators and their
/// acivated stake.
fn render_code(lamports: &[u64]) -> Result<String> {
    let mut rendered = String::new();
    let lamports_len = lamports.len();
    writeln!(
        rendered,
        "\
// Generated by `cargo xtask generate-benchmark-fixtures epoch-turnover-mainnet`.
// Source: https://api.stakewiz.com/validators?limit=2500
// Values include the full validator set, sorted descending by activated stake,
// converted from SOL to lamports and rounded to the nearest lamport.

const STAKEWIZ_MAINNET_LIKE_VALIDATOR_COUNT: usize = {lamports_len};
const STAKEWIZ_MAINNET_LIKE_ACTIVATED_STAKE_LAMPORTS: [u64; {lamports_len}] = ["
    )?;
    for lamports in lamports {
        writeln!(rendered, "    {lamports},")?;
    }
    writeln!(rendered, "];")?;
    Ok(rendered)
}

pub fn run(args: CommandArgs) -> Result<()> {
    let workspace_root = Path::new(env!("CARGO_MANIFEST_DIR"))
        .ancestors()
        .nth(2)
        .ok_or_else(|| anyhow::anyhow!("xtask crate should be nested under the repo root"))?;
    let output_path = workspace_root.join(args.output_file);
    let validators = fetch_mainnet_validators()?;

    // Convert the activated stake from SOL to lamports.
    let lamports = validators
        .iter()
        .map(|validator| (validator.activated_stake * 1_000_000_000_f64).round() as u64)
        .collect::<Vec<_>>();

    let content = render_code(&lamports)?;
    if let Some(parent) = output_path.parent() {
        fs::create_dir_all(parent)
            .with_context(|| format!("failed to create output directory {}", parent.display()))?;
    }
    fs::write(&output_path, content)
        .with_context(|| format!("failed to write {}", output_path.display()))?;
    info!("Wrote {}", output_path.display());

    Ok(())
}
